### ISSUE TITLE
Prefer std::swap to calls to malloc.

### ISSUE THREAD

**Issue by wimos-ai** [Cardinal-Space-Mining/Sick-Perception#30]
The call to malloc is a system call, requires allocation and the surrounding code is hard to reason about. Prefer the code you wrote that uses std::move because that should use stack space as the size of the swapped params is a compile-time constant, thus there are no calls to malloc in that case. Furthermore, it is easier for a programmer to reason about.

**Comment by S1ink** [comment]
Fair enough. I don't really have a preference for either one - the strategy I currently have being used just seemed less clunky. Its 16 bytes so there ain't much on the line here.
